"""
Logo upload — the only endpoint that accepts binary content.

Admin-only, and deliberately narrow: a partner logo is a small raster image, so the
endpoint accepts nothing else. Whatever arrives is decoded, downscaled and re-encoded
before it is written, so the bytes we store are ours, not the client's.

Security notes (see docs/11-security.md):
- **SVG is refused.** An SVG is XML and can carry ``<script>`` / event handlers, so a
  stored SVG served from our own origin would be a stored-XSS primitive. Only raster
  formats are allowed.
- **The format is decided by the magic bytes**, never by the client's ``Content-Type``
  or filename, both of which the client controls.
- **The stored filename is generated by us** (a uuid + an extension from our own
  allow-list), so a hostile ``filename`` can never traverse (``../../etc/passwd``) or
  pick its own extension.
- The body is capped twice: once here (``MAX_UPLOAD_BYTES``, streamed so an oversized
  file is abandoned mid-read) and once by ``BodySizeLimitMiddleware``.
- **Decompression bombs are rejected.** ``Image.open`` only parses the header, so the
  declared pixel count is checked (``MAX_IMAGE_PIXELS``) *before* the pixels are
  decoded: a 50000x50000 "PNG bomb" compresses to a few KB but would allocate
  gigabytes. It is refused with a 400.
- **A decode failure is a 400, never a 500.** Valid magic bytes + a garbage body is a
  client error, so every Pillow failure mode is funnelled into one clean response.

Storage notes:
- The image is re-encoded to **WebP** (quality 82), which beats both PNG and JPEG on
  screenshots and logos alike, and downscaled so the longest side is at most 1600px
  (never upscaled). A 5 MB phone photo lands on disk at a few dozen KB.
- **Alpha survives.** The partner logos are white-on-transparent PNGs; flattening them
  onto a white background would visually destroy them. WebP supports alpha, and RGBA
  images are re-encoded as RGBA.
- **EXIF/ICC/XMP metadata is stripped** — it can carry GPS coordinates (a privacy leak
  for anything uploaded straight from a phone) and it bloats the file.
"""

import asyncio
import io
import uuid
from pathlib import Path
from typing import Optional, Tuple

from fastapi import APIRouter, Depends, File, HTTPException, Request, UploadFile, status
from PIL import Image, ImageFile, UnidentifiedImageError

from ..config import get_settings
from ..main import limiter
from ..schemas import AdminInfo, UploadResponse
from ..security import get_current_admin

router = APIRouter(prefix="/api/admin/uploads", tags=["uploads"])

# Decoding is CPU- and memory-heavy (an image is expanded to raw RGBA in RAM). Serialise
# it: at most this many decodes run at once, so a burst of uploads — even with a stolen
# admin token — can't stack several hundred MB of concurrent bitmaps and OOM the worker.
_DECODE_SEMAPHORE = asyncio.Semaphore(2)

# Total bytes we let the uploads directory hold. Every stored file is small (a few dozen
# KB), so this is a very high ceiling in practice, but it makes disk exhaustion via an
# abused/stolen admin token impossible: past the budget, uploads are refused.
MAX_UPLOADS_DIR_BYTES = 512 * 1024 * 1024  # 512 MB

# What we accept *in*; what we store is far smaller (see compress_image). A screenshot
# straight off a phone clears a megabyte easily, so the ceiling has to allow one.
# BodySizeLimitMiddleware runs first and caps the whole multipart body, so this must stay
# below its allowance for this route (``main.MAX_UPLOAD_BODY_BYTES``, 10 MB) — the
# difference is headroom for the multipart framing around the file itself.
MAX_UPLOAD_BYTES = 8 * 1024 * 1024  # 8 MB
_CHUNK_BYTES = 64 * 1024

# Longest side of the stored image. Never upscales — a smaller logo is left as-is.
MAX_DIMENSION = 1600
_WEBP_QUALITY = 82
_WEBP_METHOD = 6  # slowest/best of Pillow's WebP effort levels; images here are small.

# Decompression-bomb ceiling: a few-KB PNG can declare 50000x50000 (2.5e9 px) and balloon
# to gigabytes once decoded. 24 MP covers any real phone photo or 4K screenshot (a 6000x4000
# shot is 24 MP) while capping a single decode's RAM: 24M px x 4 bytes RGBA ≈ 96 MB, and the
# semaphore bounds how many of those run at once.
MAX_IMAGE_PIXELS = 24_000_000
# Belt and braces: Pillow raises DecompressionBombError past 2x its own limit, which we
# pin to ours, and we check the header size explicitly as well (below).
Image.MAX_IMAGE_PIXELS = MAX_IMAGE_PIXELS
# A truncated file must fail loudly (-> 400) rather than decode to a half-grey image.
ImageFile.LOAD_TRUNCATED_IMAGES = False

# Magic-byte prefix -> the extension we store the file under. WebP is
# "RIFF....WEBP", so its check needs the bytes at offset 8 as well.
_PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
_JPEG_MAGIC = b"\xff\xd8\xff"

# Modes that carry an alpha channel (P can, via a "transparency" info key).
_ALPHA_MODES = {"RGBA", "LA", "PA", "La"}


def _extension_for(head: bytes) -> Optional[str]:
    """Return the extension implied by the file's magic bytes, or None if unsupported."""
    if head.startswith(_PNG_MAGIC):
        return "png"
    if head.startswith(_JPEG_MAGIC):
        return "jpg"
    if head[:4] == b"RIFF" and head[8:12] == b"WEBP":
        return "webp"
    return None


def _has_alpha(image: Image.Image) -> bool:
    """True if the image carries transparency in any of the forms Pillow represents it."""
    return image.mode in _ALPHA_MODES or "transparency" in image.info


def compress_image(body: bytes, source_extension: str) -> Tuple[bytes, str]:
    """Decode, downscale and re-encode ``body`` to WebP. Returns ``(bytes, "webp")``.

    Raises ``HTTPException(400)`` for anything Pillow cannot safely decode — a corrupt
    body, an unsupported variant, or a decompression bomb.

    The output is *always* the re-encode, never the original bytes: rebuilding the file
    from decoded pixels is what guarantees only image data reaches the disk (a polyglot's
    appended payload is dropped) and that EXIF/GPS is stripped. ``source_extension`` is
    accepted for signature stability but no longer influences the result.
    """
    try:
        with Image.open(io.BytesIO(body)) as source:
            # Image.open() has only parsed the header at this point, so the declared
            # dimensions are known while the pixels are still un-decoded. Refuse a bomb
            # here, before any allocation.
            width, height = source.size
            if width <= 0 or height <= 0 or width * height > MAX_IMAGE_PIXELS:
                raise _bad_image("Imagine prea mare (rezoluție).")

            source.load()  # decode; a truncated/corrupt body blows up here

            # Alpha must survive: the partner logos are white-on-transparent PNGs, and
            # flattening them onto a white background would make them invisible.
            target_mode = "RGBA" if _has_alpha(source) else "RGB"
            image = source.convert(target_mode)

        image.thumbnail((MAX_DIMENSION, MAX_DIMENSION), Image.Resampling.LANCZOS)

        # Rebuild from raw pixels: the new Image has an empty ``info``, so no EXIF (GPS!),
        # ICC profile or XMP block can ride along into the encoder.
        clean = Image.frombytes(target_mode, image.size, image.tobytes())

        buffer = io.BytesIO()
        clean.save(
            buffer,
            format="WEBP",
            quality=_WEBP_QUALITY,
            method=_WEBP_METHOD,
            exif=b"",
            icc_profile=b"",
        )
    except HTTPException:
        raise
    except Image.DecompressionBombError:
        raise _bad_image("Imagine prea mare (rezoluție).")
    except (UnidentifiedImageError, OSError, ValueError, SyntaxError, MemoryError):
        # Corrupt body, truncated file, unsupported variant, hostile input — all of them
        # are the client's problem, so none of them may surface as a 500/traceback.
        raise _bad_image()

    # Always return the re-encoded output, even when it isn't smaller. Keeping the client's
    # original bytes would let a polyglot (a valid image header with a payload appended)
    # survive on disk verbatim; the re-encode rebuilds the file from decoded pixels, so
    # nothing but image data is ever stored. `source_extension` is unused now, by design.
    return buffer.getvalue(), "webp"


def _bad_image(detail: str = "Imagine invalidă sau coruptă.") -> HTTPException:
    return HTTPException(status.HTTP_400_BAD_REQUEST, detail)


def uploads_dir() -> Path:
    """Where uploaded logos live. Inside DATA_DIR, which is a persistent volume."""
    path = Path(get_settings().data_dir) / "uploads"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _uploads_dir_bytes() -> int:
    """Total bytes currently stored under the uploads directory."""
    return sum(f.stat().st_size for f in uploads_dir().glob("*") if f.is_file())


@router.post("", response_model=UploadResponse, status_code=status.HTTP_201_CREATED)
@limiter.limit("20/minute")
async def upload_logo(
    request: Request,
    file: UploadFile = File(...),
    admin: AdminInfo = Depends(get_current_admin),
):
    """Admin only — store a partner logo and return the path to serve it from."""
    # Read with a hard ceiling: stop the moment the file exceeds the cap, so a huge
    # upload is never fully buffered.
    body = b""
    while chunk := await file.read(_CHUNK_BYTES):
        body += chunk
        if len(body) > MAX_UPLOAD_BYTES:
            raise HTTPException(
                status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                f"Logo prea mare (max {MAX_UPLOAD_BYTES // 1024} KB).",
            )

    # The magic bytes decide the format — never the Content-Type or the filename.
    extension = _extension_for(body)
    if extension is None:
        raise HTTPException(
            status.HTTP_400_BAD_REQUEST,
            "Format neacceptat. Încarcă un PNG, JPG sau WebP.",
        )

    # Refuse before doing the expensive decode if the directory is already at budget, so a
    # stolen/abused admin token can't fill the disk.
    if _uploads_dir_bytes() >= MAX_UPLOADS_DIR_BYTES:
        raise HTTPException(
            status.HTTP_507_INSUFFICIENT_STORAGE,
            "Spațiu de stocare epuizat pentru imagini.",
        )

    # Re-encode before writing: shrink it, strip its metadata, and make the stored bytes
    # ours. The decode is CPU/RAM-heavy, so serialise it behind the semaphore and run it in
    # a thread — a burst of uploads can't stack many bitmaps and OOM the event loop.
    async with _DECODE_SEMAPHORE:
        stored, extension = await asyncio.to_thread(compress_image, body, extension)

    name = f"{uuid.uuid4().hex}.{extension}"
    (uploads_dir() / name).write_bytes(stored)

    # Served by the StaticFiles mount in main.py. Site-relative on purpose: it passes
    # the frontend's LinkStr validation and survives a change of backend host.
    return UploadResponse(url=f"/api/uploads/{name}")
