"""
Logo upload — the only endpoint that accepts binary content.

Admin-only, and deliberately narrow: a partner logo is a small raster image, so the
endpoint accepts nothing else.

Security notes (see docs/11-security.md):
- **SVG is refused.** An SVG is XML and can carry ``<script>`` / event handlers, so a
  stored SVG served from our own origin would be a stored-XSS primitive. Only raster
  formats are allowed.
- **The format is decided by the magic bytes**, never by the client's ``Content-Type``
  or filename, both of which the client controls.
- **The stored filename is generated by us** (a uuid + an extension from our own
  allow-list), so a hostile ``filename`` can never traverse (``../../etc/passwd``) or
  pick its own extension.
- The body is capped twice: once here (``MAX_UPLOAD_BYTES``, streamed so an oversized
  file is abandoned mid-read) and once by ``BodySizeLimitMiddleware``.
"""

import uuid
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, Depends, File, HTTPException, Request, UploadFile, status

from ..config import get_settings
from ..main import limiter
from ..schemas import AdminInfo, UploadResponse
from ..security import get_current_admin

router = APIRouter(prefix="/api/admin/uploads", tags=["uploads"])

# A logo is a small image; anything larger is a mistake or an abuse attempt.
MAX_UPLOAD_BYTES = 512 * 1024  # 512 KB
_CHUNK_BYTES = 64 * 1024

# Magic-byte prefix -> the extension we store the file under. WebP is
# "RIFF....WEBP", so its check needs the bytes at offset 8 as well.
_PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
_JPEG_MAGIC = b"\xff\xd8\xff"


def _extension_for(head: bytes) -> Optional[str]:
    """Return the extension implied by the file's magic bytes, or None if unsupported."""
    if head.startswith(_PNG_MAGIC):
        return "png"
    if head.startswith(_JPEG_MAGIC):
        return "jpg"
    if head[:4] == b"RIFF" and head[8:12] == b"WEBP":
        return "webp"
    return None


def uploads_dir() -> Path:
    """Where uploaded logos live. Inside DATA_DIR, which is a persistent volume."""
    path = Path(get_settings().data_dir) / "uploads"
    path.mkdir(parents=True, exist_ok=True)
    return path


@router.post("", response_model=UploadResponse, status_code=status.HTTP_201_CREATED)
@limiter.limit("20/minute")
async def upload_logo(
    request: Request,
    file: UploadFile = File(...),
    admin: AdminInfo = Depends(get_current_admin),
):
    """Admin only — store a partner logo and return the path to serve it from."""
    # Read with a hard ceiling: stop the moment the file exceeds the cap, so a huge
    # upload is never fully buffered.
    body = b""
    while chunk := await file.read(_CHUNK_BYTES):
        body += chunk
        if len(body) > MAX_UPLOAD_BYTES:
            raise HTTPException(
                status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                f"Logo prea mare (max {MAX_UPLOAD_BYTES // 1024} KB).",
            )

    extension = _extension_for(body)
    if extension is None:
        raise HTTPException(
            status.HTTP_400_BAD_REQUEST,
            "Format neacceptat. Încarcă un PNG, JPG sau WebP.",
        )

    name = f"{uuid.uuid4().hex}.{extension}"
    (uploads_dir() / name).write_bytes(body)

    # Served by the StaticFiles mount in main.py. Site-relative on purpose: it passes
    # the frontend's LinkStr validation and survives a change of backend host.
    return UploadResponse(url=f"/api/uploads/{name}")
